package login.domain;

public class User {
    public User(String email, String password) {
        this.email = email;
        this.password = password;
    }

    private int id; // just used to demo retrieval of autogenerated key in UserMapper
    private String email;
    private String password; // Should be hashed and secured


     public String getEmail() {
        return email;
    }

    public void setEmail( String email ) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword( String password ) {
        this.password = password;
    }

    public int getId() {
        return id;
    }

    public void setId( int id ) {
        this.id = id;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", email='" + email + '\'' +
                ", password='" + password + '\'' +
                '}';
    }
}

